#!/usr/bin/env node
// bin2c.js — embed a binary file as a C byte array.
// Usage: node bin2c.js <in-file> <out.c> <symbol>
// Emits:  const unsigned char <symbol>[]      — the bytes
//         const unsigned long <symbol>_len     — byte count
//         const char           <symbol>_tag[]  — 8-hex crc32 of the bytes
//                                                 (used to version the extract dir)
//
// Comma-separated byte array (NOT a string literal) so MSVC's 64K
// string-literal limit never bites. Node is guaranteed on every build path
// (local nvm + CI setup-node), so a JS generator is the portable choice.
'use strict';

const fs = require('node:fs');

const [, , inPath, outPath, symbol] = process.argv;
if (!inPath || !outPath || !symbol) {
  console.error('usage: bin2c.js <in-file> <out.c> <symbol>');
  process.exit(1);
}

const buf = fs.readFileSync(inPath);

// crc32 (same polynomial as zip) — a cheap content stamp for the extract dir.
function crc32(data) {
  let crc = 0xffffffff;
  for (let i = 0; i < data.length; i++) {
    crc ^= data[i];
    for (let b = 0; b < 8; b++) {
      crc = (crc & 1) ? (crc >>> 1) ^ 0xedb88320 : crc >>> 1;
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}
const tag = crc32(buf).toString(16).padStart(8, '0');

const lines = [];
lines.push('// Generated by scripts/bin2c.js — do not edit.');
lines.push(`#include <stddef.h>`);
lines.push('');
lines.push(`const unsigned char ${symbol}[] = {`);
const PER_LINE = 20;
for (let i = 0; i < buf.length; i += PER_LINE) {
  const chunk = [];
  for (let j = i; j < Math.min(i + PER_LINE, buf.length); j++) chunk.push(buf[j]);
  lines.push('  ' + chunk.map((b) => b + ',').join(''));
}
lines.push('};');
lines.push(`const unsigned long ${symbol}_len = ${buf.length}UL;`);
lines.push(`const char ${symbol}_tag[] = "${tag}";`);
lines.push('');

fs.writeFileSync(outPath, lines.join('\n'));
console.error(`bin2c: ${inPath} (${buf.length} bytes, tag ${tag}) -> ${outPath}`);
